---
- name: Start bambuddy
  block:
    - name: Create bambuddy directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ bambuddy_directory }}"
        - "{{ bambuddy_data_directory }}"
        - "{{ bambuddy_logs_directory }}"
        - "{{ bambuddy_virtual_printer_directory }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ bambuddy_directory }}/docker-compose.yaml"
        mode: '0440'

    - name: Start bambuddy
      community.docker.docker_compose_v2:
        project_src: "{{ bambuddy_directory }}"
        state: present

  when: bambuddy_enabled

- name: Stop bambuddy
  community.docker.docker_compose_v2:
    project_src: "{{ bambuddy_directory }}"
    state: stopped
  when: not bambuddy_enabled
