---
name: watchtower

services:
  watchtower:
    container_name: "{{ watchtower_container_name }}"
    image: containrrr/watchtower:latest
    pull_policy: always
    ports:
      - "{{ watchtower_api_port }}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_HTTP_API_TOKEN: "{{ watchtower_http_api_token }}"
      WATCHTOWER_HTTP_API_METRICS: "true"
    labels:
      homepage.group: Services
      homepage.name: Watchtower
      homepage.icon: watchtower.png
      # homepage.widget.type: watchtower
      # homepage.widget.url: http://{{ ansible_nas_ip }}:{{ watchtower_api_port }}
      # homepage.widget.key: {{ watchtower_http_api_token }}
