---
# enable or disable the application
homepage_enabled: false
homepage_available_externally: false

# directories
homepage_data_directory: "{{ docker_home }}/homepage"

# network
homepage_hostname: "homepage"
homepage_port: "11111"

# docker
homepage_container_name: "homepage"
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "latest"

# specs
homepage_memory: "1g"

# settings
homepage_title: Theseus Homepage
homepage_locale: en-GB

# Homepage config files - the variables below are formatted to Homepage YAML config files
homepage_settings_yaml:
  title: "{{ homepage_title }}"
  language: "{{ homepage_locale }}"
  showStats: true

homepage_services_yaml:
  - Networking:
      - Router:
          icon: asus-router
          href: http://192.168.0.1/
          description: Asus Router

homepage_widgets_yaml:
  - greeting:
      text_size: xl
      text: Theseus
  - resources:
      cpu: true
      memory: true
      cputemp: true
      uptime: true
      units: metric # only used by cpu temp
      refresh: 60000 # optional, in ms

homepage_bookmarks_yaml:
  - Developer:
      - Github:
          - abbr: GH
            href: https://github.com/
            icon: github
      - "Hacker News":
          - abbr: HN
            href: https://news.ycombinator.com/
  - Social:
      - Reddit:
          - abbr: RE
            href: https://reddit.com/
            icon: reddit
  - Entertainment:
      - YouTube:
          - abbr: YT
            href: https://youtube.com/
            icon: youtube

homepage_allowed_hosts: "*"
