---
- name: Start logging stack
  block:
    - name: Enable logging roles
      ansible.builtin.set_fact:
        grafana_enabled: true
        minio_enabled: true
        loki_enabled: true
        promtail_enabled: true
        stats_enabled: true
  when: logging_stack_enabled is true

- name: Stop logging stack
  block:
    - name: Disable logging roles
      ansible.builtin.set_fact:
        grafana_enabled: false
        minio_enabled: false
        loki_enabled: false
        promtail_enabled: false
        stats_enabled: false
  when: logging_stack_enabled is false

- name: Import stats role
  import_role:
    name: stats

- name: Import minio role
  import_role:
    name: minio

- name: Import loki role
  import_role:
    name: loki

- name: Import promtail role
  import_role:
    name: promtail
