---
- name: Start Traefik
  block:
    - name: Create Traefik Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
      with_items:
        - "{{ traefik_config_directory }}"
        - "{{ traefik_config_directory }}/dynamic"

    - name: Create letsencrypt directories
      ansible.builtin.file:
        path: "{{ traefik_letsencrypt_directory }}"
        state: directory
        mode: '0700'

    - name: Template Traefik config.toml
      ansible.builtin.template:
        src: traefik.toml
        dest: "{{ traefik_config_directory }}/traefik.toml"
        mode: '0440'
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
      register: template_config

    - name: Dynamic auth
      ansible.builtin.template:
        src: auth.yaml
        dest: "{{ traefik_config_directory }}/dynamic/auth.yaml"
        mode: '0440'
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
      when: traefik_basic_auth_enabled

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ traefik_directory }}/docker-compose.yaml"
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: '0440'

    - name: Start Traefik
      community.docker.docker_compose_v2:
        project_src: "{{ traefik_directory }}"
        recreate: auto

    - name: Set letsencrypt permissions
      ansible.builtin.file:
        path: "{{ traefik_letsencrypt_directory }}"
        mode: u=rwX,go=
        recurse: yes
  when: traefik_enabled

- name: Stop Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_directory }}"
    state: stopped
  when: not traefik_enabled
