version: '3'

env:
  ANSIBLE_VERBOSITY: 1

tasks:
  default:
    desc: Show list of available commands
    cmds:
      - task --list

  update:
    desc: Upgrade dependencies
    cmds:
      - ansible-galaxy install -r requirements.yml

  role:
    desc: Create role
    cmds:
      - mkdir -p roles/{{.CLI_ARGS}}
      - mkdir -p roles/{{.CLI_ARGS}}/tasks
      - mkdir -p roles/{{.CLI_ARGS}}/templates
      - mkdir -p roles/{{.CLI_ARGS}}/defaults
      - touch roles/{{.CLI_ARGS}}/tasks/main.yaml
      - touch roles/{{.CLI_ARGS}}/defaults/main.yaml
      - touch roles/{{.CLI_ARGS}}/templates/docker-compose.yaml

  theseus:
    desc: Run Thesesus playbook
    cmds:
      - ansible-playbook -i inventories/local/inventory.toml playbooks/theseus.yml {{if .CLI_ARGS}}--tags "{{.CLI_ARGS}}"{{end}}

  gpu:
    desc: Run GPU playbook
    cmds:
      - ansible-playbook -i inventories/local/inventory.toml playbooks/gpu.yml {{if .CLI_ARGS}}--tags "{{.CLI_ARGS}}"{{end}}
