# {{ ansible_managed }}
[Lidarr]
api_key = {{ lidarr_api_key }}
host_url = http://{{ ansible_nas_ip }}:{{ lidarr_port }}
download_dir = {{ slskd_lidarr_downloads_directory }}
disable_sync = False

[Slskd]
api_key = {{ slskd_api_key }}
host_url = http://{{ ansible_nas_ip }}:{{ slskd_port_http }}
url_base = /
download_dir = /downloads
delete_searches = False
stalled_timeout = 3600
remote_queue_timeout = 300

[Release Settings]
use_selected_lidarr_release = False
use_most_common_tracknum = True
allow_multi_disc = True
accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
skip_region_check = False
accepted_formats = CD,Digital Media,Vinyl

[Search Settings]
search_timeout = 5000
maximum_peer_queue = 50
minimum_peer_upload_speed = 0
minimum_filename_match_ratio = 0.8
minimum_search_interval = 5
allowed_filetypes = {{ slskd_soularr_allowed_filetypes }}
ignored_users =
album_prepend_artist = False
search_type = incrementing_page
number_of_albums_to_grab = {{ slskd_soularr_albums_per_run }}
title_blacklist =
search_blacklist =
search_source = missing
failed_import_denylist = True

[Download Settings]
download_filtering = True
use_extension_whitelist = False
extensions_whitelist = lrc,nfo,txt
rename_download_folders = True

[Logging]
level = INFO
log_to_file = False
