---
- name: Set login banner
  ansible.builtin.copy:
    src: motd.txt
    dest: /etc/motd

- name: Disable default ubuntu motd files
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '-x'
  loop:
    - /etc/update-motd.d/00-header
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/90-updates-available
