[{{ nut_ups_name }}]
  desc = "{{ nut_ups_description }}"
  driver = nutdrv_qx
  port = auto
  vendorid = {{ nut_ups_vendorid }}
  productid = {{ nut_ups_productid }}
  subdriver = hunnox
  protocol = hunnox
  langid_fix = 0x0409
  novendor
  noscanlangid
  default.battery.voltage.high = {{ nut_ups_battery_voltage_high }}
  default.battery.voltage.low = {{ nut_ups_battery_voltage_low }}
