MONITOR {{ nut_ups_name }}@localhost:{{ nut_upsd_port }} 1 {{ nut_upsmon_user }} {{ nut_upsmon_password }} primary
MINSUPPLIES 1
SHUTDOWNCMD "/sbin/shutdown -h +0"
NOTIFYCMD /sbin/upssched
POLLFREQ 5
POLLFREQALERT 5
FINALDELAY 5

NOTIFYFLAG ONLINE SYSLOG+WALL+EXEC
NOTIFYFLAG ONBATT SYSLOG+WALL+EXEC
NOTIFYFLAG LOWBATT SYSLOG+WALL
NOTIFYFLAG FSD SYSLOG+WALL
NOTIFYFLAG COMMBAD SYSLOG
NOTIFYFLAG COMMOK SYSLOG
NOTIFYFLAG REPLBATT SYSLOG
NOTIFYFLAG SHUTDOWN SYSLOG+WALL
