CMDSCRIPT /etc/nut/upssched-cmd
PIPEFN /run/nut/upssched.pipe
LOCKFN /run/nut/upssched.lock

AT ONBATT * START-TIMER onbatt-shutdown {{ nut_onbattery_shutdown_seconds }}
AT ONLINE * CANCEL-TIMER onbatt-shutdown
