---
- name: Start Telegraf
  block:
    - name: Create Telegraf Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user_id }}"
        group: "{{ ansible_nas_group_id }}"
        mode: "0770"
      with_items:
        - "{{ stats_telegraf_config_directory }}"

    - name: Template telegraf.conf
      ansible.builtin.template:
        src: telegraf.conf.j2
        dest: "{{ stats_telegraf_config_directory }}/telegraf.conf"
      register: telegraf_config

    - name: Telegraf Docker Container
      community.docker.docker_container:
        name: "{{ stats_telegraf_container_name }}"
        image: "{{ stats_telegraf_image_name }}:{{ stats_telegraf_image_version }}"
        pull: true
        privileged: true
        ipc_mode: host
        ports:
          - "{{ stats_telegraf_influxdb_port }}:8086"
          - "{{ stats_telegraf_port }}:9273"
        user: "{{ ansible_nas_user_id }}:{{ ansible_nas_group_id }}"
        volumes:
          - "{{ stats_telegraf_config_directory }}:/etc/telegraf/:ro"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "/:/hostfs:ro"
          - "/etc:/hostfs/etc:ro"
          - "/proc:/hostfs/proc:ro"
          - "/sys:/hostfs/sys:ro"
          - "/var:/hostfs/var:ro"
          - "/run:/hostfs/run:ro"
        groups: "{{ telegraf_group_ids }}"
        env:
          HOST_ETC: "/hostfs/etc"
          HOST_PROC: "/hostfs/proc"
          HOST_SYS: "/hostfs/sys"
          HOST_VAR: "/hostfs/var"
          HOST_RUN: "/hostfs/run"
          HOST_MOUNT_PREFIX: "/hostfs"
        restart_policy: unless-stopped
        memory: 1g
        restart: "{{ telegraf_config is changed }}"
        networks:
          - name: "{{ o11y_network_name }}"
  when: stats_enabled is true

- name: Stop Telegraf
  block:
    - name: Stop stats_telegraf
      community.docker.docker_container:
        name: "{{ stats_telegraf_container_name }}"
        state: absent
  when: stats_enabled is false
