---
# directories
loki_minio_data_directory: "{{ docker_home }}/loki/minio"

# env
loki_minio_admin_username: admin

# network
loki_minio_api_port: "9000"
loki_minio_console_port: "9009"

# docker
loki_minio_container_name: "loki-minio"
loki_minio_image_name: "minio/minio"
loki_minio_image_version: "latest"

# specs
loki_minio_memory: "1g"
