---
# enable or disable the application
homepage_enabled: false
homepage_available_externally: false

# directories
homepage_directory: "{{ docker_home }}/homepage"
homepage_config_directory: "{{ homepage_directory }}/config"

# network
homepage_port: "11111"

# docker
homepage_container_name: "homepage"
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "latest"

# specs
homepage_memory: "1g"

# settings
homepage_title: Theseus Homepage
homepage_locale: en-GB

# Homepage config files - the variables below are formatted to Homepage YAML config files
homepage_settings_yaml:
  title: "{{ homepage_title }}"
  language: "{{ homepage_locale }}"
  showStats: true

homepage_services_yaml:

homepage_widgets_yaml:

homepage_bookmarks_yaml:

homepage_allowed_hosts: "{{ ansible_nas_ip }}:{{ homepage_port }},{{ ansible_nas_domain }},{{ ansible_nas_local_domain }}"
