---
- name: Start Plex
  block:
    - name: Create Plex Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ plex_directory }}"
        - "{{ plex_config_directory }}"
        - "{{ plex_logs }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ plex_directory }}/docker-compose.yaml"
        mode: '0440'

    - name: Start Plex
      community.docker.docker_compose_v2:
        project_src: "{{ plex_directory }}"
        state: present

  when: plex_enabled

- name: Stop Plex
  community.docker.docker_compose_v2:
    project_src: "{{ plex_directory }}"
    state: stopped
  when: not plex_enabled
