---
- name: Start InfluxDB2
  block:
    - name: Create InfluxDB2 Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ influxdb2_directory }}/config"
        - "{{ influxdb2_directory }}/wal"
        - "{{ influxdb2_data_directory }}"

    - name: Create InfluxDB2 Docker Container
      community.docker.docker_container:
        name: "{{ influxdb2_container_name }}"
        image: influxdb:2
        pull: true
        volumes:
          - "{{ influxdb2_directory }}/config:/etc/influxdb2:rw"
          - "{{ influxdb2_directory }}/wal:/var/lib/influxdb2/engine/wal:rw"
          - "{{ influxdb2_data_directory }}:/var/lib/influxdb2:rw"
        ports:
          - "{{ influxdb2_tcp_port }}:8086/tcp"
        restart_policy: unless-stopped
        labels:
          traefik.enable: "{{ influxdb2_available_externally | string }}"
          traefik.http.routers.influxdb2.rule: "Host(`{{ influxdb2_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.influxdb2.tls.certresolver: "letsencrypt"
          traefik.http.routers.influxdb2.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.influxdb2.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.influxdb2.loadbalancer.server.port: "{{ influxdb2_tcp_port }}"
  when: influxdb2_enabled is true

- name: Stop InfluxDB2
  block:
    - name: Stop InfluxDB2
      community.docker.docker_container:
        name: "{{ influxdb2_container_name }}"
        state: absent
  when: influxdb2_enabled is false
