- name: Ensure msmtp and mailx are installed
  apt:
    name:
      - msmtp
      - bsd-mailx
    state: present
    update_cache: yes

- name: Create msmtp config
  template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    mode: '0640'
    owner: root
    group: mail

- name: Ensure mailx uses msmtp
  lineinfile:
    path: /etc/mail.rc
    line: 'set sendmail="/usr/bin/msmtp"'
    create: yes
    state: present

- name: Symlink msmtp as sendmail
  file:
    src: /usr/bin/msmtp
    dest: /usr/sbin/sendmail
    state: link
    force: true

- name: Ensure users are added to mail group
  user:
    name: "{{ item }}"
    groups: mail
    append: yes
  loop: "{{ mail_group_users }}"
