---
- name: Start Crowdsec
  block:
    - name: Create Crowdsec Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
      with_items:
        - "{{ crowdsec_data_directory }}"
        - "{{ crowdsec_config_directory }}"
        - "{{ crowdsec_config_directory }}"

    - name: Template Crowdsec config
      ansible.builtin.template:
        src: acquis.yaml
        dest: "{{ crowdsec_config_directory }}/acquis.yaml"

    - name: Crowdsec Docker Container
      community.docker.docker_container:
        name: "{{ crowdsec_container_name }}"
        image: "{{ crowdsec_image_name }}:{{ crowdsec_image_version }}"
        pull: true
        ports:
          - "{{ crowdsec_port }}:8080"
        volumes:
          - "{{ crowdsec_config_directory }}:/etc/crowdsec:rw"
          - "{{ crowdsec_data_directory }}:/var/lib/crowdsec/data/:rw"
        env:
          COLLECTIONS: "crowdsecurity/linux crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
        restart_policy: unless-stopped
        memory: "{{ crowdsec_memory }}"
  when: crowdsec_enabled is true

- name: Stop Crowdsec
  block:
    - name: Stop Crowdsec
      community.docker.docker_container:
        name: "{{ crowdsec_container_name }}"
        state: absent
  when: crowdsec_enabled is false
