---
- name: Minio
  import_tasks: minio.yml

- name: Promtail
  import_tasks: promtail.yml

- name: Start Loki
  block:
    - name: Create Loki Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user_id }}"
        group: "{{ ansible_nas_group_id }}"
        mode: "0770"
      with_items:
        - "{{ loki_data_directory }}"
        - "{{ loki_config_directory }}"

    - name: Create Minio buckets for Loki
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user_id }}"
        group: "{{ ansible_nas_group_id }}"
        mode: "0770"
      with_items:
        - "{{ loki_minio_data_directory }}/data/loki-data"
        - "{{ loki_minio_data_directory }}/data/loki-ruler"

    - name: Template Loki config
      ansible.builtin.template:
        src: config.yml
        dest: "{{ loki_config_directory }}/config.yml"
      register: loki_config

    - name: Create loki Docker Container
      community.docker.docker_container:
        name: "{{ loki_container_name }}"
        image: "{{ loki_image_name }}:{{ loki_image_version }}"
        pull: true
        command: "-config.file=/etc/loki/config.yml"
        ports:
          - "{{ loki_http_port }}:3100"
          - 7946
          - 9095
        volumes:
          - "{{ loki_config_directory }}/config.yml:/etc/loki/config.yml"
          - "{{ loki_data_directory }}:/loki"
        restart_policy: unless-stopped
        memory: "{{ loki_memory }}"
        restart: "{{ loki_config is changed }}"
        labels:
          prometheus.io/scrape: "true"
          prometheus.io/port: "3100"
          prometheus.io/path: "/metrics"
        networks:
          - name: "{{ o11y_network_name }}"
        user: "{{ ansible_nas_user_id }}:{{ ansible_nas_group_id }}"

    - name: Template Grafana Loki data source
      ansible.builtin.template:
        src: grafana-datasource.yml
        dest: "{{ stats_grafana_config_directory }}/provisioning/datasources/loki.yml"
        owner: "472"
      notify: restart grafana
  when: loki_enabled is true

- name: Stop loki
  block:
    - name: Stop loki
      community.docker.docker_container:
        name: "{{ loki_container_name }}"
        state: absent
  when: loki_enabled is false
