---
- name: Start Minio
  block:
    - name: Create Minio Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user_id }}"
        group: "{{ ansible_nas_group_id }}"
        mode: "0770"
      with_items:
        - "{{ loki_minio_data_directory }}/data"

    - name: Create minio Docker Container
      community.docker.docker_container:
        name: "{{ loki_minio_container_name }}"
        image: "{{ loki_minio_image_name }}:{{ loki_minio_image_version }}"
        pull: true
        command: 'server /data --console-address ":{{ loki_minio_console_port }}"'
        volumes:
          - "{{ loki_minio_data_directory }}/data:/data"
        env:
          MINIO_ROOT_USER: "{{ loki_minio_admin_username }}"
          MINIO_ROOT_PASSWORD: "{{ loki_minio_admin_password }}"
          MINIO_PROMETHEUS_AUTH_TYPE: public
        restart_policy: unless-stopped
        memory: "{{ loki_minio_memory }}"
        user: "{{ ansible_nas_user_id }}:{{ ansible_nas_group_id }}"
        networks:
          - name: "{{ o11y_network_name }}"
  when: loki_enabled is true

- name: Stop minio
  block:
    - name: Stop minio
      community.docker.docker_container:
        name: "{{ loki_minio_container_name }}"
        state: absent
  when: loki_enabled is false
