---
- name: Import variables
  include_vars: defaults/promtail.yml

- name: Start Promtail
  block:
    - name: Create Promtail Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0770"
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
      with_items:
        - "{{ loki_promtail_config_directory }}"
        - "{{ loki_promtail_data_directory }}"

    - name: Template Promtail config
      ansible.builtin.template:
        src: promtail_config.yml
        dest: "{{ loki_promtail_config_directory }}/config.yml"

    - name: Create Promtail Docker Container
      community.docker.docker_container:
        name: "{{ loki_promtail_container_name }}"
        image: "{{ loki_promtail_image_name }}:{{ loki_promtail_image_version }}"
        pull: true
        command: "-config.file=/etc/promtail/config.yml"
        volumes:
          - "{{ loki_promtail_config_directory }}/config.yml:/etc/promtail/config.yml"
          - "{{ loki_promtail_data_directory }}:/data"
          - "/var/run/docker.sock:/var/run/docker.sock"
        restart_policy: unless-stopped
        memory: "{{ loki_promtail_memory }}"
        user: "{{ ansible_nas_user_id }}:{{ ansible_nas_group_id }}"
        networks:
          - name: "{{ o11y_network_name }}"
  when: loki_enabled is true

- name: Stop promtail
  block:
    - name: Stop promtail
      community.docker.docker_container:
        name: "{{ loki_promtail_container_name }}"
        state: absent
  when: loki_enabled is false
