name: n8n

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "{{ n8n_port }}:5678"
    labels:
      traefik.enable: "true"
      traefik.http.routers.n8n.rule: "Host(`{{ n8n_hostname }}.{{ ansible_nas_local_domain }}`)"
      traefik.http.routers.n8n.entrypoints: "web_local"
      traefik.http.services.n8n.loadbalancer.server.port: "5678"
{% if n8n_available_externally %}
      traefik.http.routers.n8n-external.rule: "Host(`{{ n8n_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.n8n-external.tls.certresolver: "letsencrypt"
      traefik.http.routers.n8n-external.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.n8n-external.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.routers.n8n-external.entrypoints: "web,websecure"
      traefik.http.routers.n8n-external.service: "n8n"
{% endif %}
      homepage.group: "Applications"
      homepage.name: "N8N"
      homepage.icon: "n8n.png"
      homepage.href: "{% if n8n_available_externally %}https://{{ n8n_hostname }}.{{ ansible_nas_domain }}{% else %}http://{{ ansible_nas_ip }}:{{ n8n_port }}{% endif %}"
      homepage.description: "Workflow automation"
    environment:
      N8N_HOST: "{% if n8n_available_externally %}https://{{ n8n_hostname }}.{{ ansible_nas_domain }}{% else %}http://{{ ansible_nas_ip }}:{{ n8n_port }}{% endif %}"
      N8N_PORT: 5678
      N8N_PROTOCOL: "{% if n8n_available_externally %}https{% else %}http{% endif %}"
      NODE_ENV: development
      WEBHOOK_URL: "{% if n8n_available_externally %}https://{{ n8n_hostname }}.{{ ansible_nas_domain }}{% else %}http://{{ ansible_nas_ip }}:{{ n8n_port }}{% endif %}/"
      GENERIC_TIMEZONE: {{ ansible_nas_timezone }}
    volumes:
      - "{{ n8n_data_folder }}:/home/node/.n8n"
      - "{{ n8n_local_files_folder }}:/files"
