---
- name: Start Stash
  block:
    - name: Create Stash Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ stash_directory }}"
        - "{{ stash_config_directory }}"
        - "{{ stash_data_content_directory }}"
        - "{{ stash_metadata_directory }}"
        - "{{ stash_cache_directory }}"
        - "{{ stash_blobs_directory }}"
        - "{{ stash_generated_directory }}"
        - "{{ stash_qbittorrent_config_directory }}"
        - "{{ stash_qbittorrent_download_directory }}"
        - "{{ stash_qbittorrent_download_directory_active }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ stash_directory }}/docker-compose.yaml"
        mode: '0440'

    - name: Start Stash
      community.docker.docker_compose_v2:
        project_src: "{{ stash_directory }}"

  when: stash_enabled

- name: Stop Stash
  community.docker.docker_compose_v2:
    project_src: "{{ stash_directory }}"
    state: stopped
  when: not stash_enabled
