---
- name: Start stash qbittorrent
  block:
    - name: Create stash qbittorrent directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ stash_qbittorrent_config_directory }}"
        - "{{ stash_qbittorrent_download_directory }}"
        - "{{ stash_qbittorrent_download_directory_active }}"

    - name: Create stash qbittorrent Docker Container
      community.docker.docker_container:
        name: "{{ stash_qbittorrent_container_name }}"
        image: "{{ stash_qbittorrent_image_name }}:{{ stash_qbittorrent_image_version }}"
        pull: true
        volumes:
          - "{{ stash_qbittorrent_download_directory }}:/downloads:rw"
          - "{{ stash_qbittorrent_config_directory }}:/config:rw"
        ports:
          - "{{ stash_qbittorrent_port_http }}:8080"
          - "{{ stash_qbittorrent_port_bt }}:6881"
          - "{{ stash_qbittorrent_port_bt }}:6881/udp"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ ansible_nas_user_id }}"
          PGID: "{{ ansible_nas_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ stash_qbittorrent_memory }}"
        labels:
          traefik.enable: "{{ stash_qbittorrent_available_externally | string }}"
          traefik.http.routers.stash-qbittorrent.rule: "Host(`{{ stash_qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.stash-qbittorrent.tls.certresolver: "letsencrypt"
          traefik.http.routers.stash-qbittorrent.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.stash-qbittorrent.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.stash-qbittorrent.middlewares: "auth@file"
          traefik.http.services.stash-qbittorrent.loadbalancer.server.port: "8080"
  when: stash_enabled

- name: Stop stash qbittorrent
  block:
    - name: Stop stash qbittorrent
      community.docker.docker_container:
        name: "{{ stash_qbittorrent_container_name }}"
        state: absent
  when: not stash_enabled
