---
- name: Start InfluxDB2
  block:
    - name: Create InfluxDB2 Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ influxdb2_directory }}/config"
        - "{{ influxdb2_directory }}/wal"
        - "{{ influxdb2_data_directory }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ influxdb2_directory }}/docker-compose.yaml"
        mode: "0440"

    - name: Start InfluxDB2
      community.docker.docker_compose_v2:
        project_src: "{{ influxdb2_directory }}"
  when: influxdb2_enabled

- name: Stop InfluxDB2
  block:
    - name: Stop InfluxDB2
      community.docker.docker_compose_v2:
        project_src: "{{ influxdb2_directory }}"
        state: stopped
  when: not influxdb2_enabled
