---
- name: Start Cloudcmd
  block:
    - name: Create Cloudcmd Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ cloudcmd_config_directory }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ cloudcmd_directory }}/docker-compose.yaml"
        mode: '0440'

    - name: Start Cloudcmd
      community.docker.docker_compose_v2:
        project_src: "{{ cloudcmd_directory }}"

  when: cloudcmd_enabled

- name: Stop Cloudcmd
  community.docker.docker_compose_v2:
    project_src: "{{ cloudcmd_directory }}"
    state: stopped
  when: not cloudcmd_enabled
