---
- name: Start Duplicati
  block:
    - name: Create Duplicati Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ duplicati_directory }}"
        - "{{ duplicati_config_directory }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ duplicati_directory }}/docker-compose.yaml"
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: '0440'

    - name: Start Duplicati
      community.docker.docker_compose_v2:
        project_src: "{{ duplicati_directory }}"

  when: duplicati_enabled

- name: Stop Duplicati
  block:
    - name: Stop Duplicati
      community.docker.docker_compose_v2:
        project_src: "{{ duplicati_directory }}"
        state: stopped
  when: not duplicati_enabled
