---
# enable or disable the application
cloudcmd_enabled: false
cloudcmd_available_externally: false

# directories
cloudcmd_config_directory: "{{ docker_home }}/cloudcmd/config"
cloudcmd_volumes:
  - "{{ docker_home }}:/application_config:rw"
  - "{{ downloads_root }}:/downloads:rw"
  - "{{ cloudcmd_config_directory }}:/config:rw"

# network
cloudcmd_hostname: "cloudcmd"
cloudcmd_port: "7373"

# specs
cloudcmd_memory: "1g"

# docker
cloudcmd_container_name: cloudcmd
