---
crowdsec_enabled: true
crowdsec_available_externally: true

crowdsec_hostname: crowdsec

# directories
crowdsec_data_directory: "{{ docker_home }}/crowdsec/data"
crowdsec_config_directory: "{{ docker_home }}/crowdsec/config"

# network
crowdsec_port: "8580"

crowdsec_container_name: "crowdsec"
crowdsec_image_name: "crowdsecurity/crowdsec"
crowdsec_image_version: "latest"

# specs
crowdsec_memory: 1g
