---
keep_packages_updated: true

ansible_nas_hostname: theseus
ansible_nas_timezone: Europe/Kyiv
ansible_nas_email: tsdaemon@gmail.com
ansible_nas_domain: t6n.app
ansible_nas_user: theseus
ansible_nas_user_id: "1001"
ansible_nas_group: users
ansible_nas_group_id: "100"

ansible_nas_from_address: "theseus@mail.t6n.app"
ansible_nas_from_name: "Theseus NAS"
ansible_nas_smtp_hostname: "smtp.eu.mailgun.org"
ansible_nas_smtp_username: "theseus@mail.t6n.app"

docker_home: /appdata
docker_network_name: "main"
docker_group_id: 987

# Samba
samba_shares_root: /mnt/data/data/media
samba_server_string: theseus
samba_map_to_guest: "Bad user"
samba_guest_account: "{{ ansible_nas_user }}"
samba_manage_directories: false
samba_server_max_protocol: SMB3
samba_server_min_protocol: SMB2

downloads_root: "/mnt/data/data"
movies_root: "{{ samba_shares_root }}/movies"
tv_root: "{{ samba_shares_root }}/tv"
books_root: "{{ samba_shares_root }}/books"
comics_root: "{{ samba_shares_root }}/comics"
photo_root: "{{ samba_shares_root }}/photo"
archive_root: "/mnt/data/archive"

# Shares you want published over Samba.
samba_shares:
  - name: movies
    comment: "Movies"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ movies_root }}"

  - name: tv
    comment: "TV Episodes"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ tv_root }}"

  - name: books
    comment: "Books"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ books_root }}"

  - name: comics
    comment: "Comics"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ comics_root }}"

  - name: photos
    comment: "Photos"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ photo_root }}"

  - name: archive
    comment: "Archive"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ archive_root }}"

# Applications

## immich
immich_enabled: true
immich_available_externally: true
immich_host: im

## qbittorrent
qbittorrent_enabled: true
qbittorrent_available_externally: false
qbittorrent_hostname: qb
qbittorrent_download_directory: "/mnt/data/data"
qbittorrent_download_directory_active: "{{ downloads_root }}/media/incomplete"

## plex
plex_enabled: true
plex_available_externally: false
plex_hostname: plex
plex_config_directory: "/mnt/data/data/plex"

## stash
stash_enabled: true
stash_available_externally: false
stash_hostname: stash
stash_data_content_directory: "/mnt/data/private/stash/content"
stash_blobs_directory: "/mnt/data/private/stash/blobs"
stash_generated_directory: "/mnt/data/private/stash/generated"

stash_qbittorrent_available_externally: false
stash_qbittorrent_hostname: qb-stash

# Storage

## influxdb2
influxdb2_enabled: true
influxdb2_data_directory: "/mnt/data/data/influxdb2"

## mariadb
mariadb_enabled: true
mariadb_data_directory: "/mnt/data/data/mariadb"

# Services

## traefik
traefik_enabled: true
traefik_dns_provider: porkbun
traefik_basic_auth_enabled: true

## crowdsec
crowdsec_enabled: false
crowdsec_data_directory: "/mnt/data/data/crowdsec"

## homepage
homepage_enabled: true
homepage_available_externally: false
homepage_bookmarks_yaml:
homepage_widgets_yaml:
  - greeting:
      text_size: xl
      text: Theseus
  - resources:
      cpu: true
      memory: true
      cputemp: true
      uptime: true
      units: metric # only used by cpu temp
      refresh: 60000 # optional, in ms
  - openmeteo:
      label: Lviv # optional
      latitude: 49.839683
      longitude: 24.029717
      timezone: Europe/Kyiv # optional
      units: metric # or imperial
      cache: 5 # Time in minutes to cache API responses, to stay within limits
      format: # optional, Intl.NumberFormat options
        maximumFractionDigits: 1
homepage_services_yaml:
  - External:
      - Router:
          icon: asus-router
          href: "http://192.168.0.1/"
          description: Asus Router
      - Home Assistant:
          icon: home-assistant.png
          href: "http://192.168.0.100/"
          description: Home Assistant
homepage_settings_yaml:
  title: "Theseus Homepage"
  language: "en-GB"
  showStats: true
  layout:
    - Media:
    - Services:
    - Networking:
    - Monitoring:
    - External:
  maxGroupColumns: 8
  useEqualHeights: true
  statusStyle: "dot"
  quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    showSearchSuggestions: true
    hideVisitURL: true
    provider: google

## duplicati
duplicati_enabled: true
duplicati_available_externally: false
duplicati_hostname: dpl

## cloudcmd
cloudcmd_enabled: true
cloudcmd_port: "7373"

## pihole
pihole_enabled: true
pihole_dns1: "8.8.8.8"
pihole_dns2: "1.1.1.1"

## wireguard
wireguard_enabled: true
wireguard_available_externally: false

# o11y

## loki
loki_enabled: true
loki_data_directory: "/mnt/data/data/loki"
loki_minio_data_directory: "/mnt/data/data/loki/minio"
loki_promtail_data_directory: "/mnt/data/data/loki/promtail"

## stats
stats_enabled: true
stats_grafana_available_externally: false
stats_internet_speed_test_enabled: true
stats_prometheus_data_directory: "/mnt/data/data/stats/prometheus"
stats_grafana_data_directory: "/mnt/data/data/stats/grafana"
stats_telegraf_influxdb_port: "8186"

## netdata
netdata_enabled: false
netdata_claim_token: "HjAD-r4SQXKz-FzaU2OxuCzZ8kA_uWpTRpgfO-sB-0GmR8z96_AZbuE-deXORBC9LkMegAVHZcZJp8mFBnWEa8kzzTY0Ggxa_k_0-gEWazPiCNaVEIhcFDBdwxr3e5qh92Cmv2U"
netdata_claim_rooms: "07487960-50b7-4f28-b9ff-70980ebe3832"
netdata_claim_url: "https://app.netdata.cloud"
