---
jellyfin_enabled: false

# directories
jellyfin_directory: "{{ docker_home }}/jellyfin"
jellyfin_config_directory: "{{ jellyfin_directory }}/config"
jellyfin_cache_directory: "{{ jellyfin_directory }}/cache"
jellyfin_movies_directory: "{{ movies_root }}"
jellyfin_tv_directory: "{{ tv_root }}"
jellyfin_music_directory: "{{ music_root }}"

# uid / gid
jellyfin_user_id: "{{ ansible_nas_user_id }}"
jellyfin_group_id: "{{ ansible_nas_group_id }}"

# network
jellyfin_hostname: "jellyfin"
jellyfin_port: "8096"

# docker
jellyfin_container_name: "jellyfin"
jellyfin_image_name: "lscr.io/linuxserver/jellyfin"
jellyfin_image_version: "latest"

# GPU (hardware transcoding; enable in Jellyfin's admin UI once GPU is passed through)
jellyfin_gpu_enabled: true
