---
flaresolverr_enabled: false
flaresolverr_available_externally: false

# directories
flaresolverr_directory: "{{ docker_home }}/flaresolverr"

# network
flaresolverr_hostname: "flaresolverr"
flaresolverr_port: "8191"

# docker
flaresolverr_container_name: "flaresolverr"
flaresolverr_image_name: "ghcr.io/flaresolverr/flaresolverr"
flaresolverr_image_version: "latest"

# specs
flaresolverr_memory: "2g"
flaresolverr_shm_size: "1gb"
flaresolverr_log_level: "info"
