---
- name: Start lidarr
  block:
    - name: Create lidarr Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ lidarr_directory }}"
        - "{{ lidarr_config_directory }}"
        - "{{ lidarr_music_directory }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ lidarr_directory }}/docker-compose.yaml"
        mode: '0440'

    - name: Start lidarr
      community.docker.docker_compose_v2:
        project_src: "{{ lidarr_directory }}"
  when: lidarr_enabled

- name: Stop lidarr
  community.docker.docker_compose_v2:
    project_src: "{{ lidarr_directory }}"
    state: stopped
  when: not lidarr_enabled
