services:
  coolify:
    image: "${REGISTRY_URL:-ghcr.io}/coollabsio/coolify:${LATEST_IMAGE:-latest}"
    volumes:
      - type: bind
        source: {{ coolify_source_directory }}/.env
        target: /var/www/html/.env
        read_only: true
      - {{ coolify_ssh_directory }}:/var/www/html/storage/app/ssh
      - {{ coolify_applications_directory }}:/var/www/html/storage/app/applications
      - {{ coolify_databases_directory }}:/var/www/html/storage/app/databases
      - {{ coolify_services_directory }}:/var/www/html/storage/app/services
      - {{ coolify_backups_directory }}:/var/www/html/storage/app/backups
      - {{ coolify_webhooks_during_maintenance_directory }}:/var/www/html/storage/app/webhooks-during-maintenance
    environment:
      APP_ENV: ${APP_ENV:-production}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-256M}
      PHP_FPM_PM_CONTROL: ${PHP_FPM_PM_CONTROL:-dynamic}
      PHP_FPM_PM_START_SERVERS: ${PHP_FPM_PM_START_SERVERS:-1}
      PHP_FPM_PM_MIN_SPARE_SERVERS: ${PHP_FPM_PM_MIN_SPARE_SERVERS:-1}
      PHP_FPM_PM_MAX_SPARE_SERVERS: ${PHP_FPM_PM_MAX_SPARE_SERVERS:-10}
    env_file:
      - {{ coolify_source_directory }}/.env
    ports:
      - "{{ coolify_port }}:8080"
    expose:
      - "{{ coolify_port }}"
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      soketi:
        condition: service_healthy
    labels:
      traefik.enable: "true"
      traefik.http.routers.coolify.rule: "Host(`{{ coolify_hostname }}.{{ ansible_nas_local_domain }}`)"
      traefik.http.routers.coolify.entrypoints: "web_local"
      traefik.http.services.coolify.loadbalancer.server.port: "8080"
{% if coolify_available_externally %}
      traefik.http.routers.coolify-external.rule: "Host(`{{ coolify_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.coolify-external.tls.certresolver: "letsencrypt"
      traefik.http.routers.coolify-external.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.coolify-external.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.routers.coolify-external.entrypoints: "web,websecure"
      traefik.http.routers.coolify-external.service: "coolify"
{% endif %}
      homepage.group: "Applications"
      homepage.name: "Coolify"
      homepage.icon: "sh-coolify.png"
      homepage.href: "http://{{ ansible_nas_ip }}:{{ coolify_port }}"
      homepage.description: "Application management"
    user: "{{ coolify_user_id }}:{{ ansible_nas_group_id }}"
  postgres:
    volumes:
      - {{ coolify_postgres_data_directory }}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE:-coolify}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}", "-d", "${DB_DATABASE:-coolify}" ]
      interval: 5s
      retries: 10
      timeout: 2s
    user: "{{ coolify_user_id }}:{{ ansible_nas_group_id }}"
  redis:
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - coolify-redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 10
      timeout: 2s
  soketi:
    image: '${REGISTRY_URL:-ghcr.io}/coollabsio/coolify-realtime:1.0.9'
    ports:
      - "${SOKETI_PORT:-6001}:6001"
      - "6002:6002"
    volumes:
      - {{ coolify_ssh_directory }}:/var/www/html/storage/app/ssh
    environment:
      APP_NAME: "${APP_NAME:-Coolify}"
      SOKETI_DEBUG: "${SOKETI_DEBUG:-false}"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:6001/ready && wget -qO- http://127.0.0.1:6002/ready || exit 1" ]
      interval: 5s
      retries: 10
      timeout: 2s
    user: "{{ coolify_user_id }}:{{ ansible_nas_group_id }}"

volumes:
  coolify-db:
    name: coolify-db
  coolify-redis:
    name: coolify-redis

networks:
  coolify:
    external: true
