---
- name: Start Pi-hole
  block:
    - name: Disable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        enabled: false
        state: stopped
        masked: true

    - name: Create Pi-hole Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
        mode: "770"
      with_items:
        - "{{ pihole_directory }}"
        - "{{ pihole_config_directory }}"
        - "{{ pihole_dnsmasq_directory }}"

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ pihole_directory }}/docker-compose.yaml"
        mode: "0440"

    - name: Start Pi-hole
      community.docker.docker_compose_v2:
        project_src: "{{ pihole_directory }}"

    - name: Remove resolv.conf
      ansible.builtin.file:
        path: "/etc/resolv.conf"
        state: absent

    - name: Create resolv.conf to itself
      ansible.builtin.copy:
        dest: "/etc/resolv.conf"
        content: |
          nameserver {{ ansible_nas_ip }}
        mode: "0644"
  when: pihole_enabled

- name: Stop Pi-hole
  block:
    - name: Stop Pi-hole
      community.docker.docker_compose_v2:
        project_src: "{{ pihole_directory }}"
        state: stopped

    - name: Create resolv.conf to public DNS servers
      ansible.builtin.copy:
        dest: "/etc/resolv.conf"
        content: |
          nameserver {{ pihole_dns1 }}
          nameserver {{ pihole_dns2 }}
        mode: "0644"
  when: not pihole_enabled
