---
- name: Start Portainer
  block:
    - name: Create Portainer Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ portainer_directory }}"
        - "{{ portainer_data_directory }}"

    - name: Docker Compose file
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ portainer_directory }}/docker-compose.yaml"
        mode: '0440'

    - name: Start Portainer
      community.docker.docker_compose_v2:
        project_src: "{{ portainer_directory }}"
  when: portainer_enabled

- name: Stop Portainer
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_directory }}"
    state: stopped
  when: not portainer_enabled
