---
- name: Start Homepage
  block:
    - name: Create Homepage Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0770'
        owner: "{{ ansible_nas_user }}"
        group: "{{ ansible_nas_group }}"
      with_items:
        - "{{ homepage_directory }}"
        - "{{ homepage_config_directory }}"

    - name: Template config files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ homepage_config_directory }}/{{ item }}"
      with_items:
        - bookmarks.yaml
        - docker.yaml
        - settings.yaml
        - services.yaml
        - widgets.yaml
      register: homepage_config

    - name: Create docker-compose.yaml
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: "{{ homepage_directory }}/docker-compose.yaml"
        mode: '0440'

    - name: Create Homepage Docker Container
      community.docker.docker_compose_v2:
        project_src: "{{ homepage_directory }}"
  when: homepage_enabled

- name: Stop Homepage
  block:
    - name: Stop Homepage
      community.docker.docker_compose_v2:
        project_src: "{{ homepage_directory }}"
        state: stopped
  when: not homepage_enabled
