---
- name: Setup Theseus
  hosts: all
  become: true
  roles:
    ###
    ### Requirements
    ###
    - role: ansible-nas-users
      tags:
        - ansible-nas-users
        - ansible-nas
        - users

    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint

    - role: geerlingguy.docker
      vars:
        docker_apt_filename: download_docker_com_linux_ubuntu
      tags:
        - docker
        - skip_ansible_lint

    - role: mail
      tags:
        - mail

    ###
    ### Ansible-NAS Roles
    ###
    - role: ansible-nas-general
      tags:
        - ansible-nas-general
        - ansible-nas

    - role: ansible-nas-docker
      tags:
        - ansible-nas-docker
        - ansible-nas
    ###
    ### Stacks
    ###

    - role: logging
      tags:
        - logging


    ###
    ### Applications
    ###
    - role: duplicati
      tags:
        - duplicati

    - role: qbittorrent
      tags:
        - qbittorrent

    - role: plex
      tags:
        - plex

    - role: influxdb2
      tags:
        - influxdb2

    - role: mariadb
      tags:
        - mariadb

    - role: traefik
      tags:
        - traefik
