- name: Download hddfancontrol deb package
  ansible.builtin.get_url:
    url: "https://github.com/desbma/hddfancontrol/releases/download/2.0.3/hddfancontrol_2.0.3-1_amd64.deb"
    dest: "/tmp/hddfancontrol_2.0.3-1_amd64.deb"
    mode: "0644"

- name: Install hddfancontrol deb package
  ansible.builtin.apt:
    deb: "/tmp/hddfancontrol_2.0.3-1_amd64.deb"
    state: present
    install_recommends: false

- name: Clean up downloaded deb package
  ansible.builtin.file:
    path: "/tmp/hddfancontrol_2.0.3-1_amd64.deb"
    state: absent
