---
- name: Setup Theseus
  hosts: theseus
  become: true
  vars:
    ansible_nas_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  roles:
    ###
    ### Server configuration
    ###
    - role: users
      tags:
        - users
        - configuration

    - role: vladgh.samba.server
      tags:
        - samba
        - skip_ansible_lint
        - configuration

    - role: wsdd
      tags:
        - wsdd
        - samba
        - configuration

    - role: geerlingguy.nfs
      tags:
        - nfs
        - skip_ansible_lint
        - configuration

    - role: geerlingguy.docker
      vars:
        docker_apt_filename: download_docker_com_linux_ubuntu
      tags:
        - docker
        - skip_ansible_lint
        - configuration

    - role: mail
      tags:
        - mail
        - configuration

    - role: security
      tags:
        - security
        - configuration

    - role: disk
      tags:
        - disk
        - configuration

    - role: general
      tags:
        - general
        - configuration

    - role: child-lock
      tags:
        - child-lock
        - configuration

    - role: docker
      tags:
        - docker
        - configuration

    ###
    ### Storage
    ###
    - role: influxdb2
      tags:
        - influxdb2
        - storage

    - role: mariadb
      tags:
        - mariadb
        - storage

    ###
    ### Services
    ###
    - role: duplicati
      tags:
        - duplicati
        - services

    - role: traefik
      tags:
        - traefik
        - services

    - role: watchtower
      tags:
        - watchtower
        - services

    # - role: crowdsec
    #   tags:
    #     - crowdsec
    #     - services

    - role: homepage
      tags:
        - homepage
        - services

    - role: cloudcmd
      tags:
        - cloudcmd
        - services

    - role: pihole
      tags:
        - pihole
        - services

    - role: wireguard
      tags:
        - wireguard
        - services

    - role: portainer
      tags:
        - portainer
        - services

    ###
    ### Observability
    ###
    - role: o11y
      tags:
        - o11y

    - role: loki
      tags:
        - loki
        - o11y

    - role: stats
      tags:
        - stats
        - o11y

    - role: phoenix
      tags:
        - phoenix
        - o11y

    # - role: netdata
    #   tags:
    #     - netdata
    #     - o11y

    ###
    ### Applications
    ###
    - role: qbittorrent
      tags:
        - qbittorrent
        - applications

    - role: plex
      tags:
        - plex
        - applications

    - role: immich
      tags:
        - immich
        - applications

    - role: stash
      tags:
        - stash
        - applications

    - role: n8n
      tags:
        - n8n
        - applications

    - role: coolify
      tags:
        - coolify
        - applications

    - role: dokku
      tags:
        - dokku
        - applications

    - role: ubooquity
      tags:
        - ubooquity
        - applications

    - role: calibre
      tags:
        - calibre
        - applications

    - role: frigate
      tags:
        - frigate
        - applications

    - role: gramps
      tags:
        - gramps
        - applications

    - role: baserow
      tags:
        - baserow
        - applications
