---
name: "qbittorrent"

services:
  qbittorrent:
    container_name: "{{ qbittorrent_container_name }}"
    image: "{{ qbittorrent_image_name }}:{{ qbittorrent_image_version }}"
    pull_policy: always
    volumes:
      - "{{ qbittorrent_download_directory }}:/downloads:rw"
      - "{{ qbittorrent_config_directory }}:/config:rw"
    ports:
      - "{{ qbittorrent_port_http }}:8080"
      - "{{ qbittorrent_port_bt }}:6881"
      - "{{ qbittorrent_port_bt }}:6881/udp"
    environment:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ qbittorrent_user_id }}"
      PGID: "{{ qbittorrent_group_id }}"
    restart: unless-stopped
    mem_limit: "{{ qbittorrent_memory }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_local_domain }}`)"
      traefik.http.routers.qbittorrent.entrypoints: "web_local"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "8080"
{% if qbittorrent_available_externally %}
      traefik.http.routers.qbittorrent-external.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.qbittorrent-external.tls.certresolver: "letsencrypt"
      traefik.http.routers.qbittorrent-external.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.qbittorrent-external.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.routers.qbittorrent-external.entrypoints: "web,websecure"
      traefik.http.routers.qbittorrent-external.service: "qbittorrent"
      traefik.http.routers.qbittorrent-external.middlewares: "auth@file"
{% endif %}
      homepage.group: Applications
      homepage.name: qBittorrent
      homepage.icon: qbittorrent
      homepage.href: "{% if qbittorrent_available_externally %}https://{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}{% else %}http://{{ ansible_nas_ip }}:{{ qbittorrent_port_http }}{% endif %}"
      homepage.description: Torrent client
      homepage.widget.type: qbittorrent
      homepage.widget.url: "http://{{ ansible_nas_ip }}:{{ qbittorrent_port_http }}"
      homepage.widget.enableLeechProgress: "true"
